contact_links:
  - name: 🤔 Questions and Help
    url: https://discord.com/channels/747741246667227157/883355707146141737
    about: This issue tracker is not for support questions. Please refer to the Alephium community's Discord.
